[project]
name = "site-project-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standart]>=0.120.0",
    "pyodbc>=5.3.0",
    "sqlalchemy>=2.0.44",
]
